#!/usr/bin/expect -f
set host [lindex $argv 0]
#exec touch test.txt
set user "backup"
set pw "backup"
set Pw "Punch1123!"
#log_user 0
spawn telnet $host
expect "Username:"
send "$user\r"
expect "Password:"
send "$pw\r"
expect ">"
send "enable\n"
expect "Password:"
send "$Pw\r"
#expect "#"
#expect { "end"{ send "exit\n" } }
#send "show running-config\n"
#log_user 1
#spawn sleep 5
interact